import streamlit as st

# Configuration must be the first command
st.set_page_config(
    page_title="CSCA20 Financial App",
    layout="wide"
)

# --- Content for the Home Page ---
st.title("💸 Financial Tracker Home Dashboard")
st.write("Welcome to your personal financial tracking application. Please use the navigation menu on the left (automatically generated by Streamlit) to explore your Profile, set Goals, and view Visualizations.")
st.markdown("---")
st.subheader("Getting Started")
st.markdown(
    """
    1. **Go to Profile** to securely enter and save your income and spending details.
    2. **Go to Goals** to set your saving targets and deadlines.
    3. **Go to Visualization** to see charts and summaries of your current data flow.
    """
)
st.info("Ensure all three files (`app.py`, `goals.py`, `profile.py`, and `visualization.py`) are correctly placed in the root folder or the `pages` subfolder for the sidebar to show all links.")